### ISSUE TITLE
ArrayIndexOutOfBoundsException on down arrow in scheduling view

### ISSUE THREAD

**Issue by lmann99** [lmann99/libreplan#17]
ERROR [24-January 12:55:23] [https-jsse-nio-8443-exec-1] org.zkoss.zk.ui.impl.UiEngineImpl  -
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418)
        at java.util.ArrayList.get(ArrayList.java:431)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
        at org.libreplan.web.tree.TreeController$Renderer$KeyboardNavigationHandler.focusCorrectBox(TreeController.java:650)
        at org.libreplan.web.tree.TreeController$Renderer$KeyboardNavigationHandler.focusGoDown(TreeController.java:616)
        at org.libreplan.web.tree.TreeController$Renderer$KeyboardNavigationHandler.focusGoDown(TreeController.java:600)
        at org.libreplan.web.tree.TreeController$Renderer$KeyboardNavigationHandler.moveFocusTo(TreeController.java:514)
        at org.libreplan.web.tree.TreeController$Renderer$KeyboardNavigationHandler.lambda$register$0(TreeController.java:486)
        at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3030)
        at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3001)
        at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2942)
        at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
        at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:536)
        at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:463)

**Comment by lmann99** [comment]
Fixed by pull request #18
